### ISSUE TITLE
Linter not showing errors in code

### ISSUE THREAD

**Issue by levitsky** [SublimeLinter/SublimeLinter-pyflakes#15]
Hi,

I hope you can help me out here. For some time now, the linter has stopped showing errors. It just shows `pyflakes(ok)` in the status bar, even when I have errors like unused variables, unbound names, etc. Before that, it worked just fine, and I'm not sure when it stopped working and why.

I have no user-defined config for linting. My pyflakes version is `2.2.0 Python 3.8.2 on Linux` and it shows errors just fine when used from terminal on the same file. I'll be happy to provide additional info if you explain how to do so. I have tried reinstalling SublimeLinter and SiblimeLinter-pyflakes.

Update: I found a panel for linter output and it says: `myfile.py: No lint results`.
Update 2: I tried installing another linter (flake8) and that one works, so it should be something specific to this linter.

**Comment by kaste** [comment]
Yeah, they broke the format on `2.2.0`.  We have to fix the regex.  Take a look at the regex in `linter.py` in this repo.  Compare that to the output `pyflakes` produces on the Terminal.

**Comment by levitsky** [comment]
Apparently it doesn't match because the regex expects a colon after `col` (if `col` is present). With 2.1.9, `col` was not there at all, with 2.2.0 it's there but there is no colon after the column:

```
myfilepy:4:1 'glob.glob' imported but unused  # 2.2.0
myfilepy.py:4: 'glob.glob' imported but unused  # 2.1.9
```

**Comment by kaste** [comment]
Yeah! Look at that shitty regex, and I even wrote it!  But hell, maybe pyflakes whatever v <1.0.0 had a completely different output.

**Comment by levitsky** [comment]
It served long enough :)

**Comment by kaste** [comment]
Fixed in https://github.com/SublimeLinter/SublimeLinter-pyflakes/releases/tag/1.3.2
