### ISSUE TITLE
Ignore #NOQA commented lines

### ISSUE THREAD

**Issue by scorphus** [SublimeLinter/SublimeLinter-pyflakes#3]
I have a line with an [`F401`](https://flake8.readthedocs.org/en/2.4.1/warnings.html#warning-error-codes) that I want it to be ignored, so I added a `# NOQA` comment at the end of it. But SublimeLinter-pyflakes still warns me:

![screen shot 2015-08-17 at 7 43 03 pm](https://cloud.githubusercontent.com/assets/2112697/9318248/48d397f8-4518-11e5-9920-08a98911b450.png)

What am I missing? 

Thanks!

**Comment by braver** [comment]
You're confusing pyflakes with flake8. Pyflakes has no configuration and no "noqa" comments, that's flake8.
