### ISSUE TITLE
'undefined name' error highlights first match in line regardless of whether it is the error

### ISSUE THREAD

**Issue by pbx** [SublimeLinter/SublimeLinter-pyflakes#4]
Minimal test case:
`[1, 2, 3].index(index)`
Lint this line, and you'll (correctly) get an **undefined name 'index'** error. However, the first 'index' (a legitimate method call) is the one highlighted, not the second (which is the NameError).

pyflakes doesn't return the character index, just a line number. Most of the time the first match (which is what I presume the linter is doing to choose what to highlight) is the correct spot. But when it's not, the mistake is potentially confusing. 

One idea for less misleading behavior here is to highlight the entire line.

**Comment by braver** [comment]
There really isn't anything we can do here, the output from pylint doesn't provide any information we can use.
