### ISSUE TITLE
respect [flake8] section in tox.ini of current project

### ISSUE THREAD

**Issue by temoto** [SublimeLinter/SublimeLinter-pyflakes#5]
Hello.

First, thank you for sublime-pyflakes plugin, it's very helpful.

Please advice how to configure or where to patch to make sublimelinter-pyflakes respect [flake8] settings in tox.ini. Other tools (like pep8) support reading settings from tox.ini so that's where I keep linter config for some projects.

**Comment by braver** [comment]
A lot has happened since this issue was opened. Some of what we did probably fixed this. If it's still a problem, let us know.
